feat: Выполнение спринта №14 согласно ТЗ.
Wirt150/java-shareit pull request #2
Opened 2022-11-09 23:56 UTC by Wirt150

Выполнение 14 спринта.

2022-11-10 16:42 UTC, Frilock requested changes
Добрый вечер, все здорово, пару мелких комментариев оставил, но они не значительные.

2022-11-10 16:42 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/entity/Booking.java
> +@Table(name = "booking", schema = "public")
Схема public дефолтная, можно не указывать в аннотации Table

2022-11-10 16:42 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/entity/Booking.java
> +    @Column(name = "id")
Для Id Column можно не ставить, поле также называется в БД

2022-11-10 16:42 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/entity/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
fetch = FetchType.EAGER - тоже дефолтное значение по моему, но тут ладно, пусть явно будет

2022-11-10 16:42 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/entity/Booking.java
> +@Data
Будьте аккуратны:
https://habr.com/ru/company/haulmont/blog/564682/
https://stackoverflow.com/questions/40516058/using-lomboks-data-and-builder-on-entity

2022-11-10 16:42 UTC, Frilock commented on src/main/java/ru/practicum/shareit/config/validator/ValidateDate.java
> +            return value.getEnd().isAfter(value.getStart());
Не помню, вроде уже задавал Вам этот вопрос, тут value.getEnd null не вернет?

2022-11-10 16:42 UTC, Frilock commented on src/main/resources/schema.sql
> +    description varchar(1024)                           NOT NULL,
Размерность которую тут указываете пропищите еще в Column аннотации для строковых полей

2022-11-12 10:37 UTC, Wirt150 commented on src/main/java/ru/practicum/shareit/config/validator/ValidateDate.java
> +            return value.getEnd().isAfter(value.getStart());
Поставил валидацию на уровне объекта.

2022-11-12 11:38 UTC, Frilock approved these changes
Принято

2022-11-12 11:43 UTC, merged